shared_memory:
	gcc -std=c99 shared_memory.c -o solution

daemon:
	gcc daemon.c -o solution

sig_count:
	gcc sig_count.c -o solution

multiplexing:
	gcc -std=c99 multiplexing.c -o solution

zero_count:
	gcc zero_count.c -o solution
